# Generated by Django 3.0.3 on 2020-03-03 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='coordinateX',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='coordinateY',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='isWall',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='workedOn',
            field=models.BooleanField(default=False),
        ),
    ]
